# Settings.yml
---
conf.py:
  project: TypoScript Reference
  copyright: 2000-2014
  version: 6.2
  release: 6.2
  intersphinx_mapping:
    t3cmsapi:
    - http://typo3.org/api/typo3cms/
    - null
    t3api:
    - http://docs.typo3.org/typo3cms/CoreApiReference/
    - null
    t3tssyntax:
    - http://docs.typo3.org/typo3cms/TyposcriptSyntaxReference/
    - null
...