# Settings.yml
---
conf.py:
  project: TypoScript Reference
  copyright: 2000-2013
  version: 6.0
  release: 6.0
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-Typoscript
    github_branch: 6-0
...
